name: Lighthouse CI

on: [push]

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse CI
        run: |
          npm install && npm install -g @lhci/cli@0.12.x
          npm run build
          lhci autorun
